/**
 * One-time: download Poppins woff2 latin-subset files from Google Fonts and
 * generate self-hosted @font-face CSS at public/fonts/poppins.css.
 *
 * Run: node scripts/download-fonts.mjs
 *
 * After running, swap the `@import url('https://fonts.googleapis.com/...');`
 * line in src/styles/global.css for the local file.
 */

import fs from 'node:fs/promises';
import path from 'node:path';

const WEIGHTS = [200, 400, 600, 700, 900];
const FONT_DIR = 'public/fonts/poppins';
const CSS_OUT = 'public/fonts/poppins.css';
const CHROME_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

await fs.mkdir(FONT_DIR, { recursive: true });

// Fetch Google Fonts CSS with a Chrome UA so we get woff2 URLs (not TTF).
const cssRes = await fetch(
  `https://fonts.googleapis.com/css2?family=Poppins:wght@${WEIGHTS.join(';')}&display=swap`,
  { headers: { 'User-Agent': CHROME_UA } }
);
if (!cssRes.ok) throw new Error(`Google Fonts CSS fetch failed: ${cssRes.status}`);
const css = await cssRes.text();

// Split by `@font-face { ... }` blocks and pick the `/* latin */` block for
// each weight. Google's CSS includes devanagari / latin-ext / latin subsets;
// we only need latin for an English AU site.
const blocks = css.split('/* latin */').slice(1).map((b) => '/* latin */' + b.split(/\/\*\s*\w+(-\w+)?\s*\*\//)[0]);

let outCss = '/* Self-hosted Poppins (latin subset only).\n';
outCss += ' * Generated by scripts/download-fonts.mjs from Google Fonts CSS API.\n';
outCss += ` * Weights: ${WEIGHTS.join(', ')} | Subset: latin (U+0000-00FF + Latin Extended-A core).\n`;
outCss += ' */\n\n';

const downloaded = [];
let i = 0;
for (const block of blocks) {
  const weightMatch = block.match(/font-weight:\s*(\d+)/);
  const urlMatch = block.match(/url\(([^)]+)\)/);
  if (!weightMatch || !urlMatch) continue;
  const weight = weightMatch[1];
  const remoteUrl = urlMatch[1];
  const filename = `poppins-${weight}.woff2`;
  const localPath = path.join(FONT_DIR, filename);

  const res = await fetch(remoteUrl, { headers: { 'User-Agent': CHROME_UA } });
  if (!res.ok) {
    console.warn(`  skipping weight ${weight}: ${res.status}`);
    continue;
  }
  const buf = Buffer.from(await res.arrayBuffer());
  await fs.writeFile(localPath, buf);
  downloaded.push({ weight, filename, size: buf.length });

  const unicodeMatch = block.match(/unicode-range:\s*([^;]+);/);
  outCss += `@font-face {\n`;
  outCss += `  font-family: 'Poppins';\n`;
  outCss += `  font-style: normal;\n`;
  outCss += `  font-weight: ${weight};\n`;
  outCss += `  font-display: swap;\n`;
  outCss += `  src: url('/fonts/poppins/${filename}') format('woff2');\n`;
  if (unicodeMatch) {
    outCss += `  unicode-range: ${unicodeMatch[1].trim()};\n`;
  }
  outCss += `}\n\n`;
  i++;
}

await fs.writeFile(CSS_OUT, outCss);

console.log('Downloaded:');
for (const d of downloaded) {
  console.log(`  ${d.filename}  ${(d.size / 1024).toFixed(1)} KB`);
}
console.log(`\nCSS: ${CSS_OUT}`);
console.log('\nNext: in src/styles/global.css, replace the @import url() line with:');
console.log('  @import url(\'/fonts/poppins.css\');');
