/**
 * One-time: download Archivo + Montserrat woff2 latin-subset files from
 * Google Fonts and generate self-hosted @font-face CSS at public/fonts/fonts.css.
 *
 * Run: node scripts/download-fonts.mjs
 *
 * After running, add this to BaseLayout.astro <head>:
 *   <link rel="preload" href="/fonts/fonts.css" as="style" />
 *   <link rel="stylesheet" href="/fonts/fonts.css" />
 */

import fs from 'node:fs/promises';
import path from 'node:path';

const FONT_DIR = 'public/fonts';
const CSS_OUT = 'public/fonts/fonts.css';
const CHROME_UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FONTS = [
  { family: 'Archivo', weights: [400, 500, 600, 700], subdir: 'archivo' },
  { family: 'Montserrat', weights: [600, 700, 800], subdir: 'montserrat' },
];

await fs.mkdir(FONT_DIR, { recursive: true });

let outCss = '/* Self-hosted Archivo + Montserrat (latin subset only).\n';
outCss += ' * Generated by scripts/download-fonts.mjs from Google Fonts CSS API.\n';
outCss += ' */\n\n';

for (const { family, weights, subdir } of FONTS) {
  const dir = path.join(FONT_DIR, subdir);
  await fs.mkdir(dir, { recursive: true });

  const url = `https://fonts.googleapis.com/css2?family=${family.replace(' ', '+')}:wght@${weights.join(';')}&display=swap`;
  const cssRes = await fetch(url, { headers: { 'User-Agent': CHROME_UA } });
  if (!cssRes.ok) throw new Error(`Google Fonts CSS fetch failed for ${family}: ${cssRes.status}`);
  const css = await cssRes.text();

  const latinBlocks = css.split('/* latin */').slice(1).map(
    (b) => '/* latin */' + b.split(/\/\*\s*\w+(-\w+)?\s*\*\//)[0]
  );

  for (const block of latinBlocks) {
    const weightMatch = block.match(/font-weight:\s*(\d+)/);
    const urlMatch = block.match(/url\(([^)]+)\)/);
    if (!weightMatch || !urlMatch) continue;
    const weight = weightMatch[1];
    const remoteUrl = urlMatch[1];
    const filename = `${subdir}-${weight}.woff2`;
    const localPath = path.join(dir, filename);

    const res = await fetch(remoteUrl, { headers: { 'User-Agent': CHROME_UA } });
    if (!res.ok) { console.warn(`  skipping ${family} ${weight}: ${res.status}`); continue; }
    const buf = Buffer.from(await res.arrayBuffer());
    await fs.writeFile(localPath, buf);
    console.log(`  ${filename}  ${(buf.length / 1024).toFixed(1)} KB`);

    const unicodeMatch = block.match(/unicode-range:\s*([^;]+);/);
    outCss += `@font-face {\n`;
    outCss += `  font-family: '${family}';\n`;
    outCss += `  font-style: normal;\n`;
    outCss += `  font-weight: ${weight};\n`;
    outCss += `  font-display: swap;\n`;
    outCss += `  src: url('/fonts/${subdir}/${filename}') format('woff2');\n`;
    if (unicodeMatch) outCss += `  unicode-range: ${unicodeMatch[1].trim()};\n`;
    outCss += `}\n\n`;
  }
}

await fs.writeFile(CSS_OUT, outCss);
console.log(`\nWrote: ${CSS_OUT}`);
console.log('\nNext: add to BaseLayout.astro <head>:');
console.log("  <link rel=\"preload\" href=\"/fonts/fonts.css\" as=\"style\" />");
console.log("  <link rel=\"stylesheet\" href=\"/fonts/fonts.css\" />");
