# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "46ec96c0f38f777b87d5e5a77938e1aa"
name = "Baitboards Dev Site"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_product_listings,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[access.storefront]
scopes = "unauthenticated_read_product_listings,unauthenticated_read_product_inventory,unauthenticated_read_collection_listings,unauthenticated_read_product_tags,unauthenticated_read_selling_plans"

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-04"
